# Generated by Django 3.2.9 on 2021-11-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gins', '0002_remove_distillery_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distillery',
            old_name='hasvisitorcetre',
            new_name='hasvisitorcentre',
        ),
    ]
