# Generated by Django 3.2.9 on 2021-12-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gins', '0003_rename_hasvisitorcetre_distillery_hasvisitorcentre'),
    ]

    operations = [
        migrations.AddField(
            model_name='distillery',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
