# Generated by Django 3.2.9 on 2021-11-29 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gins', '0003_rename_hasvisitorcetre_distillery_hasvisitorcentre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('first_created_on', models.DateTimeField(auto_now_add=True)),
                ('last_editted_on', models.DateTimeField(auto_now=True)),
                ('distillery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gins.distillery')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
